version: "3"

services:
  infisical-standalone:
    container_name: infisical-standalone
    build:
      context: .
      dockerfile: Dockerfile.standalone-infisical
    env_file: .env
    restart: always
    ports:
      - 8000:80
      - 8443:443
